spring.application.name=HACCP MES 1.0
spring.profiles.active=mes
mes.project-name=mes
# prod ? ??, local ????

server.address=0.0.0.0

server.forward-headers-strategy=framework
server.max-http-header-size=30000

# Ã¬ÂÂÃ«ÂÂ Ã«Â¡ÂÃªÂ·Â¸Ã¬ÂÂÃ¬ÂÂ Ã¬ÂÂÃªÂ°Â (60Ã¬Â´Â, ÃªÂ¸Â°Ã«Â³Â¸Ã¬ÂÂ 1800(30Ã«Â¶Â))
server.servlet.session.timeout=36000

server.servlet.context-path=/
spring.mvc.servlet.path=/
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.html

#spring.devtools.livereload.enabled=true
spring.web.locale=ko
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB


server.error.include-exception=true
server.error.include-stacktrace=ALWAYS
server.error.whitelabel.enabled=true


spring.thymeleaf.prefix=classpath:templates/
spring.thymeleaf.suffix=.html
#spring.thymeleaf.mode=HTML
#spring.thymeleaf.encoding=UTF-8
#spring.thymeleaf.servlet.content-type=text/html

spring.thymeleaf.cache=false
#spring.thymeleaf.check-template-location=true

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.devtools.restart.enabled=false


#create: ÃªÂ¸Â°Ã¬Â¡Â´Ã­ÂÂÃ¬ÂÂ´Ã«Â¸Â Ã¬ÂÂ­Ã¬Â Â Ã­ÂÂ Ã«ÂÂ¤Ã¬ÂÂ Ã¬ÂÂÃ¬ÂÂ± (DROP + CREATE)
#create-drop: createÃ¬ÂÂ ÃªÂ°ÂÃ¬ÂÂ¼Ã«ÂÂ Ã¬Â¢ÂÃ«Â£ÂÃ¬ÂÂÃ¬Â ÂÃ¬ÂÂ Ã­ÂÂÃ¬ÂÂ´Ã«Â¸Â DROP
#update: Ã«Â³ÂÃªÂ²Â½Ã«Â¶ÂÃ«Â§Â Ã«Â°ÂÃ¬ÂÂ(Ã¬ÂÂ´Ã¬ÂÂDBÃ¬ÂÂÃ¬ÂÂÃ«ÂÂ Ã¬ÂÂ¬Ã¬ÂÂ©Ã­ÂÂÃ«Â©Â´ Ã¬ÂÂÃ«ÂÂ¨)
#validate: Ã¬ÂÂÃ­ÂÂ°Ã­ÂÂ°Ã¬ÂÂ Ã­ÂÂÃ¬ÂÂ´Ã«Â¸ÂÃ¬ÂÂ´ Ã¬Â ÂÃ¬ÂÂ Ã«Â§Â¤Ã­ÂÂÃ«ÂÂÃ¬ÂÂÃ«ÂÂÃ¬Â§ÂÃ«Â§Â Ã­ÂÂÃ¬ÂÂ¸
#none: Ã¬ÂÂ¬Ã¬ÂÂ©Ã­ÂÂÃ¬Â§Â Ã¬ÂÂÃ¬ÂÂ(Ã¬ÂÂ¬Ã¬ÂÂ¤Ã¬ÂÂ Ã¬ÂÂÃ«ÂÂ ÃªÂ°ÂÃ¬ÂÂ´Ã¬Â§ÂÃ«Â§Â ÃªÂ´ÂÃ«Â¡ÂÃ¬ÂÂ noneÃ¬ÂÂ´Ã«ÂÂ¼ÃªÂ³Â  Ã­ÂÂÃ«ÂÂ¤.)
spring.jpa.hibernate.ddl-auto=none

spring.data.jpa.repositories.enabled=true
spring.data.jdbc.repositories.enabled=false

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
#spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults= false
spring.jpa.open-in-view=false

#Ã¬Â½ÂÃ¬ÂÂÃ¬ÂÂ SQLÃ¬ÂÂ Ã«Â³Â´ÃªÂ¸Â° Ã¬Â¢ÂÃªÂ²Â Ã«ÂÂÃ¬ÂÂ¸ ÃªÂ²ÂÃ¬ÂÂ¸Ã¬Â§Â
spring.jpa.properties.hibernate.format_sql=true
#Ã¬Â½ÂÃ¬ÂÂÃ¬ÂÂ SQLÃ¬ÂÂ Ã«ÂÂÃ¬ÂÂ¸ ÃªÂ²ÂÃ¬ÂÂ¸Ã¬Â§Â
spring.jpa.properties.hibernate.show-sql=true
spring.jpa.properties.hibernate.use_sql_comments=false
#logging.level.org.hibernate=debug
logging.level.org.hibernate=info
#spring.jpa.properties.hibernate.highlight_sql=true
#logging.level.org.hibernate.SQL=debug
#logging.level.org.hibernate.type.descriptor.sql=trace

#spring.session.jdbc.initialize-schema=always
spring.session.store-type=jdbc
spring.batch.jdbc.initialize-schema=never
spring.session.jdbc.initialize-schema=never
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.batch.BatchAutoConfiguration


# application.properties
#mybatis.type-aliases-package=mes.domain.model
#mybatis.type-handlers-package=mes.domain.typehandler
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.default-fetch-size=100
mybatis.configuration.default-statement-timeout=30

logging.level.root=info
logging.level.mes.app.PopBill=INFO
site=mes21
mqtt_host=10.10.10.231
mqtt_web_port=9001
hmi_topic=${site}_hmi_data


# =========================
# MES BASE / PROJECT PATH
# =========================
# OSÃ«Â³Â ÃªÂ¸Â°Ã«Â³Â¸ ÃªÂ²Â½Ã«Â¡Â
mes.base-path=${BASE_PATH}
mes.project-path=${mes.base-path}/${mes.project-name}

# =========================
# Ã­ÂÂÃ¬ÂÂ¼ Ã¬ÂÂÃ¬Â¹Â
# =========================
mes_form_path=${mes.project-path}/mes_form

# =========================
# Ã¬ÂÂÃ«Â¡ÂÃ«ÂÂ Ã¬ÂÂÃ¬Â¹Â
# =========================
file_upload_path=${mes.project-path}

# =========================
# Ã¬ÂÂÃ¬ÂÂ Ã¬ÂÂÃ«Â¡ÂÃ«ÂÂ
# =========================
file_temp_upload_path=${mes.project-path}/upload_temp

weather.api.endpoint=https://apis.data.go.kr/1360000/VilageFcstInfoService_2.0

#mail
spring.mail.host=smtp.naver.com
spring.mail.port=465
spring.mail.username=actasshare@naver.com
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.default-encoding=UTF-8


popbill.linkId=ACTAS
popbill.isTest=true
popbill.isIpRestrictOnOff=true

openai.api.key=${OPENAI_API_KEY}

