spring.application.name=HACCP MES 1.0
spring.profiles.active=mes
mes.project-name=mes
# prod ? ??, local ????

server.address=0.0.0.0

server.forward-headers-strategy=framework
server.max-http-header-size=30000

# ìë ë¡ê·¸ìì ìê° (60ì´, ê¸°ë³¸ì 1800(30ë¶))
server.servlet.session.timeout=36000

server.servlet.context-path=/
spring.mvc.servlet.path=/
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.html

#spring.devtools.livereload.enabled=true
spring.web.locale=ko
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB


server.error.include-exception=true
server.error.include-stacktrace=ALWAYS
server.error.whitelabel.enabled=true


spring.thymeleaf.prefix=classpath:templates/
spring.thymeleaf.suffix=.html
#spring.thymeleaf.mode=HTML
#spring.thymeleaf.encoding=UTF-8
#spring.thymeleaf.servlet.content-type=text/html

spring.thymeleaf.cache=false
#spring.thymeleaf.check-template-location=true

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.devtools.restart.enabled=false


#create: ê¸°ì¡´íì´ë¸ ì­ì  í ë¤ì ìì± (DROP + CREATE)
#create-drop: createì ê°ì¼ë ì¢ë£ìì ì íì´ë¸ DROP
#update: ë³ê²½ë¶ë§ ë°ì(ì´ìDBììë ì¬ì©íë©´ ìë¨)
#validate: ìí°í°ì íì´ë¸ì´ ì ì ë§¤íëìëì§ë§ íì¸
#none: ì¬ì©íì§ ìì(ì¬ì¤ì ìë ê°ì´ì§ë§ ê´ë¡ì noneì´ë¼ê³  íë¤.)
spring.jpa.hibernate.ddl-auto=none

spring.data.jpa.repositories.enabled=true
spring.data.jdbc.repositories.enabled=false

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
#spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults= false
spring.jpa.open-in-view=false

#ì½ìì SQLì ë³´ê¸° ì¢ê² ëì¸ ê²ì¸ì§
spring.jpa.properties.hibernate.format_sql=true
#ì½ìì SQLì ëì¸ ê²ì¸ì§
spring.jpa.properties.hibernate.show-sql=true
spring.jpa.properties.hibernate.use_sql_comments=false
#logging.level.org.hibernate=debug
logging.level.org.hibernate=info
#spring.jpa.properties.hibernate.highlight_sql=true
#logging.level.org.hibernate.SQL=debug
#logging.level.org.hibernate.type.descriptor.sql=trace

#spring.session.jdbc.initialize-schema=always
spring.session.store-type=jdbc
spring.batch.jdbc.initialize-schema=never
spring.session.jdbc.initialize-schema=never
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.batch.BatchAutoConfiguration


# application.properties
#mybatis.type-aliases-package=mes.domain.model
#mybatis.type-handlers-package=mes.domain.typehandler
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.default-fetch-size=100
mybatis.configuration.default-statement-timeout=30

logging.level.root=info
logging.level.mes.app.PopBill=INFO
site=mes21
mqtt_host=10.10.10.231
mqtt_web_port=9001
hmi_topic=${site}_hmi_data


# =========================
# MES BASE / PROJECT PATH
# =========================
# OSë³ ê¸°ë³¸ ê²½ë¡
mes.base-path=${BASE_PATH}
mes.project-path=${mes.base-path}/${mes.project-name}

# =========================
# íì¼ ìì¹
# =========================
mes_form_path=${mes.project-path}/mes_form

# =========================
# ìë¡ë ìì¹
# =========================
file_upload_path=${mes.project-path}

# =========================
# ìì ìë¡ë
# =========================
file_temp_upload_path=${mes.project-path}/upload_temp

weather.api.endpoint=https://apis.data.go.kr/1360000/VilageFcstInfoService_2.0

api.key=ZoyXbEkXMf1%2BvmjVOx7694aR%2Bj4J1jAaVAXI5%2BqIo3UbEWpx8ztE3iJ07oICtuZkh%2Fs6hsjfTG6NWsm98fUxhg%3D%3D

invoice.api.key=K7xHNeWiuFdFPZ9l4QJeq7QPKK1MsOujrFcXOAi%2BeG%2BWhdYtxNEtOuLOBq%2B2iHX0NKly9IPbeKSDbNYzhK%2BD5A%3D%3D

#Geocoder APi
Geocoder.Key=105C2324-CB47-33C9-BF8F-CDEDB6686AF9

#mail
spring.mail.host=smtp.naver.com
spring.mail.port=465
spring.mail.username=kimyouli0330@naver.com
spring.mail.password=G5WKQC5MUHHJ
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.default-encoding=UTF-8


#ACTAS : N1QIQbkIw0SdR7fMBnMGebK3M5L1LghIYxLUGn+pCCE= (?????)
#ONITSYSTEM : ONITSYSTEM : ef/n6IlFRMGFABqKCvKIyvuKmNAXEymTFUffbYd4KZM=
popbill.linkId=ACTAS
popbill.secretKey=N1QIQbkIw0SdR7fMBnMGebK3M5L1LghIYxLUGn+pCCE=
popbill.isTest=true
popbill.isIpRestrictOnOff=true

openai.api.key=${OPENAI_API_KEY}

